name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - 14.x
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm-install
      run: npm install --ignore-scripts

    - name: build
      run: npx node-pre-gyp install --build-from-source

    - name: test
      run: npm run test

    - name: pack
      run: npx node-pre-gyp package

    - uses: actions/upload-artifact@v2
      with:
        name: lib
        path: lib
    - name: test
      run: npm test
